### ISSUE TITLE
[Feature Request] Current Discord role in rank embed

### ISSUE THREAD

**Issue by shawn695** [BlueDevelopersInc/DiscordSRVUtils#124]
A suggestion when doing /rank user in discord on the rank embed instead of saying rank 2 that it shows the name of that rank from the discord role @role

**Comment by BlueTree242** [comment]
Feature is already possible, but the placeholder was long, so i made it easier. 

**NOTE**
A better leveling roles system was already implemented into the plugin, now a level can have multiple roles, and commands, if you try upgrade your `leveling-roles.json` will be converted into the new format `leveling-rewards.json`, which has no docs, you can come on our discord if you have any questions.

You can use this `${#stats.roles.isEmpty() ? \"No Role\" : #stats.roles.get(0).name}` placeholder, it will say `No Role` if there is no role. Also, since it is possible to have multiple roles per level now, this placeholder will display the first one in the list (in your leveling-rewards.json)

**PLEASE BACKUP YOUR leveling-roles.json THIS IS EXPERIMENTAL**
You can download the development build from [here](https://ci.bluetree242.ml/job/DiscordSRVUtils)
