### ISSUE TITLE
discordsrv link bug

### ISSUE THREAD

**Issue by TISnoob** [BlueDevelopersInc/DiscordSRVUtils#127]
```diff
  [Thu 14:18:37 INFO ] Linked together .TISmc6noob and T I S#4357
- [Thu 14:18:37 ERROR DiscordSRVUtils] The following error have a high chance to be caused by DiscordSRVUtils. Report at https://discordsrvutils.xyz/support and not discordsrv's Discord.
! [Thu 14:18:37 WARN ] java.lang.NullPointerException: Cannot invoke "tk.bluetree242.discordsrvutils.systems.leveling.PlayerStats.getLevel()" because "stats" is null
! [Thu 14:18:37 WARN ] 	at DiscordSRVUtils-1.2.10.jar//tk.bluetree242.discordsrvutils.listeners.discordsrv.DiscordSRVListener.lambda$onLink$0(DiscordSRVListener.java:63)
! [Thu 14:18:37 WARN ] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
! [Thu 14:18:37 WARN ] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
! [Thu 14:18:37 WARN ] 	at java.base/java.lang.Thread.run(Thread.java:1589)
- [Thu 14:18:37 ERROR DiscordSRVUtils] Read the note above the error Please.```


Can't link account when user has no xp (I think)

**Comment by BlueTree242** [comment]
This bug was already fixed a while ago, and you can download latest development build from [here](https://ci.bluetree242.ml/job/DiscordSRVUtils)

**NOTE: ** The error is ignorable, which means you can safely ignore if it happens, if you decide go update to a dev build you will notice some changes to leveling system, so it is highly recommended to keep on your current version until i am ready to release the development builds

**Comment by BlueTree242** [comment]
This bug was already fixed a while ago, and you can download latest development build from [here](https://ci.bluetree242.ml/job/DiscordSRVUtils)

**NOTE: ** The error is ignorable, which means you can safely ignore if it happens, if you decide go update to a dev build you will notice some changes to leveling system, so it is highly recommended to keep on your current version until i am ready to release the development builds
