### ISSUE TITLE
[Feature Request] add commands

### ISSUE THREAD

**Issue by ItsMuffin24** [BlueDevelopersInc/DiscordSRVUtils#128]
add command for check namemc profile player name for easy to see player skin, player name history, player uuid
add more command: check server status, if the server on or off and how many players online, and server ip and version

**Comment by BlueTree242** [comment]
Hello, status command is not possible because if server is offline it won't be able to respond, you can use the status system which is a message that updates when needed, and it can include server ip & version. unfortunately, namemc profile command will not be added and this is because of future project [PreBot](https://github.com/BlueTree242/PreBot), this is a much bigger project and any new feature requests to this plugin will nicely be added as a PreBot plugin (except for small ones).

I will keep this issue open for 24 hours if you have any questions.
